# CI de Nível 01 - Disparo Manual através de clique

# nome da pipeline
name: "01 - Execução Manual"
permissions:
  contents: write

# gatilhos / triggers - regras de disparo
# gatilho manual = workflow_dispatch

on:
  workflow_dispatch:

#tarefas dentro da pipeline = jobs

jobs:
  #nome do job
  e2e-tests:
    # maquina onde o job vai rodar
    runs-on: ubuntu-latest

    # passos do job
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalção do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      # instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      #   instalação das dependências
      - name: Instalando dependências
        run: yarn install

      # instalação dos Browsers do Playwright
      - name: Instalando Browsers do Playwright
        run: yarn playwright install --with-deps

      # executar os testes e2e
      - name: Executando testes e2e
        run: yarn run e2e

      # 1. Este passo baixa o histórico anterior para manter os gráficos de evolução
      - name: Coletar histórico do Allure
        uses: actions/checkout@v4
        if: ${{ always() }}
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages-dir

      # 2. Este passo junta os testes novos com o histórico e monta a página web
      - name: Gerar Allure Report com Histórico
        uses: simple-elf/allure-report-action@master
        if: ${{ always() }}
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      # 3. Este passo publica a página web gerada no GitHub Pages do seu repositório
      - name: Publicar relatório no GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
