# nome da pipeline
name: "03 - Execução por Deploy"
permissions:
  contents: write

# gatilhos / triggers - regras de disparo
# gatilho manual = workflow_dispatch
# gatilho agendado = schedule
# gatilho por conclusão de outra pipeline = workflow_run

on:
  workflow_run:
    workflows: ["01 - Execução Manual", "02 - Execução Agendada"]
    types:
      - completed

#tarefas dentro da pipeline = jobs

jobs:
  #nome do job
  e2e-tests:
    # maquina onde o job vai rodar
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    # passos do job
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalção do node
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      # instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      #   instalação das dependências
      - name: Instalando dependências
        run: yarn

      # instalação dos Browsers do Playwright
      - name: Instalando Browsers do Playwright
        run: yarn playwright install --with-deps

      # executar os testes e2e
      - name: Executando testes e2e
        run: yarn run e2e

     # Relatorios
      # 1. Baixa o histórico anterior para manter os gráficos de evolução
      - name: Coletar histórico do Allure
        uses: actions/checkout@v4
        if: ${{ always() }}
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages-dir

      # 2. Gera o relatório consolidando os resultados na pasta 'allure-report'
      - name: Gerar Allure Report com Histórico
        uses: simple-elf/allure-report-action@master
        if: ${{ always() }}
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: deploy # <-- Nome limpo da pasta!
          keep_reports: 20

      # 3. Publica a pasta raiz gerada (allure-report) para dentro da subpasta no GitHub Pages
      - name: Publicar relatório no GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report # <-- Aponta para o report compilado
          destination_dir: deploy # <-- Força a gravação exata dentro desta pasta na nuvem
